### ISSUE TITLE
Debuffs from AoE effects are not shown

### ISSUE THREAD

**Issue by wojas007** [bkader/TidyPlates_WoTLK#1]
Hello,
I noticed that debuffs that do not have duration themselves (from AoE effects) are not shown. It counts for things like: Hurricane, Death and Decay, Frost Trap, Explosive Trap, etc. Some of them may be pointless, but some of them could be worth displaying (like Frost Trap slow).

If you find these somehow important then maybe it's good to look into it.

**Comment by bkader** [comment]
@wojas007, do you mean this debuff?

![TidyPlates_FrostTrap](https://user-images.githubusercontent.com/4732702/110241142-94c4c700-7f4f-11eb-8038-0e371ec231d0.png)

**Comment by wojas007** [comment]
Yes, so why I don't see this?

**Comment by bkader** [comment]
This is sadly a server-related issue! On some servers this shows, on others it doesn't.

**Comment by MaelKoT** [comment]
I'm not sure, but there seems to be a different problem here. These AoE debuffs dont have duration - and in addon debuffs without duration are not displayed, they are ignored.

**Comment by bkader** [comment]
If they don't have duration then the addon is working fine.
If they do have duration but the addon isn't showing them, then there is an issue.

You can see on my screenshot that on my local server it's showing. But it doesn't really matter, as long as they are ignored and not shown, like they should be, this is no longer considered an issue.

**Comment by MaelKoT** [comment]
> You can see on my screenshot that on my local server it's showing.

But i cant see debuffs without a duration on your screenshot...

**Comment by bkader** [comment]
> But i cant see debuffs without a duration on your screenshot...

This issue was put here to remember it and try to tweak the addon, because after few tests, we noticed that those debuffs should not show because on warmane or other servers they don't have duration (unlike what you see on my screenshot, they do have duration). So technically, if they don't have duration, this is not an issue. I hope you understand what I mean.

**Comment by MaelKoT** [comment]
To be honest, I'm not really understand...

Do you mean, original addon shows only debuffs with duration, and debuffs without durations not shown; so if in all most popular 3.3.5 servers these debuffs dont have duration - then fck this servers? Something like this?

**Comment by bkader** [comment]
No.
When we were doing tests, we noticed that on local servers those debuffs have durations, but on some if not all private servers they don't have duration. They might show but without durations.
I closed this issue because it is not related to the addon but rather to the server, that's everything I meant.
